# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import raft_pb2 as raft__pb2


class RaftStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Join = channel.unary_unary(
                '/Raft/Join',
                request_serializer=raft__pb2.JoinRequest.SerializeToString,
                response_deserializer=raft__pb2.JoinResponse.FromString,
                )
        self.PutRequest = channel.unary_unary(
                '/Raft/PutRequest',
                request_serializer=raft__pb2.PutMessage.SerializeToString,
                response_deserializer=raft__pb2.PutReply.FromString,
                )
        self.GetRequest = channel.unary_unary(
                '/Raft/GetRequest',
                request_serializer=raft__pb2.GetMessage.SerializeToString,
                response_deserializer=raft__pb2.GetReply.FromString,
                )
        self.DelRequest = channel.unary_unary(
                '/Raft/DelRequest',
                request_serializer=raft__pb2.DelMessage.SerializeToString,
                response_deserializer=raft__pb2.DelReply.FromString,
                )
        self.VoteRequest = channel.unary_unary(
                '/Raft/VoteRequest',
                request_serializer=raft__pb2.VoteMessage.SerializeToString,
                response_deserializer=raft__pb2.VoteReply.FromString,
                )
        self.HeartBeat = channel.unary_unary(
                '/Raft/HeartBeat',
                request_serializer=raft__pb2.HBMessage.SerializeToString,
                response_deserializer=raft__pb2.HBReply.FromString,
                )
        self.SpreadLog = channel.unary_unary(
                '/Raft/SpreadLog',
                request_serializer=raft__pb2.LogMessage.SerializeToString,
                response_deserializer=raft__pb2.LogReply.FromString,
                )
        self.SpreadCommit = channel.unary_unary(
                '/Raft/SpreadCommit',
                request_serializer=raft__pb2.CommitMessage.SerializeToString,
                response_deserializer=raft__pb2.CommitReply.FromString,
                )


class RaftServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoteRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartBeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpreadLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpreadCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=raft__pb2.JoinRequest.FromString,
                    response_serializer=raft__pb2.JoinResponse.SerializeToString,
            ),
            'PutRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.PutRequest,
                    request_deserializer=raft__pb2.PutMessage.FromString,
                    response_serializer=raft__pb2.PutReply.SerializeToString,
            ),
            'GetRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRequest,
                    request_deserializer=raft__pb2.GetMessage.FromString,
                    response_serializer=raft__pb2.GetReply.SerializeToString,
            ),
            'DelRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.DelRequest,
                    request_deserializer=raft__pb2.DelMessage.FromString,
                    response_serializer=raft__pb2.DelReply.SerializeToString,
            ),
            'VoteRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteRequest,
                    request_deserializer=raft__pb2.VoteMessage.FromString,
                    response_serializer=raft__pb2.VoteReply.SerializeToString,
            ),
            'HeartBeat': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartBeat,
                    request_deserializer=raft__pb2.HBMessage.FromString,
                    response_serializer=raft__pb2.HBReply.SerializeToString,
            ),
            'SpreadLog': grpc.unary_unary_rpc_method_handler(
                    servicer.SpreadLog,
                    request_deserializer=raft__pb2.LogMessage.FromString,
                    response_serializer=raft__pb2.LogReply.SerializeToString,
            ),
            'SpreadCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.SpreadCommit,
                    request_deserializer=raft__pb2.CommitMessage.FromString,
                    response_serializer=raft__pb2.CommitReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Raft', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Raft(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Raft/Join',
            raft__pb2.JoinRequest.SerializeToString,
            raft__pb2.JoinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Raft/PutRequest',
            raft__pb2.PutMessage.SerializeToString,
            raft__pb2.PutReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Raft/GetRequest',
            raft__pb2.GetMessage.SerializeToString,
            raft__pb2.GetReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DelRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Raft/DelRequest',
            raft__pb2.DelMessage.SerializeToString,
            raft__pb2.DelReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VoteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Raft/VoteRequest',
            raft__pb2.VoteMessage.SerializeToString,
            raft__pb2.VoteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HeartBeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Raft/HeartBeat',
            raft__pb2.HBMessage.SerializeToString,
            raft__pb2.HBReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SpreadLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Raft/SpreadLog',
            raft__pb2.LogMessage.SerializeToString,
            raft__pb2.LogReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SpreadCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Raft/SpreadCommit',
            raft__pb2.CommitMessage.SerializeToString,
            raft__pb2.CommitReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
